drop function if exists public.mt_immutable_timestamp(text);
drop function if exists public.mt_immutable_timestamptz(text);
drop function if exists public.mt_immutable_time(text);
drop function if exists public.mt_immutable_date(text);
drop function if exists public.mt_grams_vector(text,boolean);
drop function if exists public.mt_grams_query(text,boolean);
drop function if exists public.mt_grams_array(text,boolean);
drop function if exists public.mt_jsonb_append(jsonb,text[],jsonb,boolean);
drop function if exists public.mt_jsonb_copy(jsonb,text[],text[]);
drop function if exists public.mt_jsonb_duplicate(jsonb,text[],jsonb);
drop function if exists public.mt_jsonb_fix_null_parent(jsonb,text[]);
drop function if exists public.mt_jsonb_increment(jsonb,text[],numeric);
drop function if exists public.mt_jsonb_insert(jsonb,text[],jsonb,integer,boolean);
drop function if exists public.mt_jsonb_move(jsonb,text[],text);
drop function if exists public.mt_jsonb_path_to_array(text,char(1));
drop function if exists public.mt_jsonb_remove(jsonb,text[],jsonb);
drop function if exists public.mt_jsonb_patch(jsonb,jsonb);
drop function if exists public.mt_safe_unaccent(boolean,text);
DROP TABLE IF EXISTS public.mt_doc_deadletterevent CASCADE;
drop function if exists public.mt_upsert_deadletterevent(JSONB, varchar, uuid, uuid);
drop function if exists public.mt_insert_deadletterevent(JSONB, varchar, uuid, uuid);
drop function if exists public.mt_update_deadletterevent(JSONB, varchar, uuid, uuid);
DROP TABLE IF EXISTS public.mt_doc_tagcount CASCADE;
drop function if exists public.mt_upsert_tagcount(JSONB, varchar, varchar, integer);
drop function if exists public.mt_insert_tagcount(JSONB, varchar, varchar, integer);
drop function if exists public.mt_update_tagcount(JSONB, varchar, varchar, integer);
drop function if exists public.mt_overwrite_tagcount(JSONB, varchar, varchar, integer);
DROP TABLE IF EXISTS public.mt_streams CASCADE;
DROP TABLE IF EXISTS public.mt_events CASCADE;
DROP SEQUENCE IF EXISTS public.mt_events_sequence;
DROP TABLE IF EXISTS public.mt_event_progression CASCADE;
drop function if exists public.mt_mark_event_progression(varchar, bigint);
drop function if exists public.mt_archive_stream(uuid);
drop function if exists public.mt_quick_append_events(uuid, varchar, varchar, uuid[], varchar[], varchar[], jsonb[]);
