AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nexus Image Storage Infrastructure'

Parameters:
  OriginalImageBucketName:
    Type: String
    Default: nexus-original-images
    Description: Name of the bucket for original images
  
  ProcessedImageBucketName:
    Type: String
    Default: nexus-processed-images
    Description: Name of the bucket for processed images
  
  ThumbnailBucketName:
    Type: String
    Default: nexus-thumbnails
    Description: Name of the bucket for thumbnails

Resources:
  OriginalImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OriginalImageBucketName

  OriginalImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OriginalImageBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyNonImageUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${OriginalImageBucket.Arn}/*'
            Condition:
              StringNotLike:
                's3:content-type':
                  - 'image/jpeg'
                  - 'image/jpg'
                  - 'image/png'
                  - 'image/gif'
                  - 'image/webp'
          - Sid: DenyOversizedUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${OriginalImageBucket.Arn}/*'
            Condition:
              NumericGreaterThan:
                's3:content-length': 10485760  # 10MB in bytes

  ProcessedImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProcessedImageBucketName

  ProcessedImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProcessedImageBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyNonImageUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${ProcessedImageBucket.Arn}/*'
            Condition:
              StringNotLike:
                's3:content-type':
                  - 'image/jpeg'
                  - 'image/jpg'
                  - 'image/png'
                  - 'image/gif'
                  - 'image/webp'
          - Sid: DenyOversizedUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${ProcessedImageBucket.Arn}/*'
            Condition:
              NumericGreaterThan:
                's3:content-length': 10485760  # 10MB in bytes

  ThumbnailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ThumbnailBucketName

  ThumbnailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ThumbnailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyNonImageUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${ThumbnailBucket.Arn}/*'
            Condition:
              StringNotLike:
                's3:content-type':
                  - 'image/jpeg'
                  - 'image/jpg'
                  - 'image/png'
                  - 'image/gif'
                  - 'image/webp'
          - Sid: DenyOversizedUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${ThumbnailBucket.Arn}/*'
            Condition:
              NumericGreaterThan:
                's3:content-length': 10485760  # 10MB in bytes

Outputs:
  OriginalImageBucketName:
    Description: Name of the original image bucket
    Value: !Ref OriginalImageBucket
    Export:
      Name: !Sub '${AWS::StackName}-OriginalImageBucket'
  
  OriginalImageBucketArn:
    Description: ARN of the original image bucket
    Value: !GetAtt OriginalImageBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OriginalImageBucketArn'

  ProcessedImageBucketName:
    Description: Name of the processed image bucket
    Value: !Ref ProcessedImageBucket
    Export:
      Name: !Sub '${AWS::StackName}-ProcessedImageBucket'
  
  ProcessedImageBucketArn:
    Description: ARN of the processed image bucket
    Value: !GetAtt ProcessedImageBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProcessedImageBucketArn'

  ThumbnailBucketName:
    Description: Name of the thumbnail bucket
    Value: !Ref ThumbnailBucket
    Export:
      Name: !Sub '${AWS::StackName}-ThumbnailBucket'
  
  ThumbnailBucketArn:
    Description: ARN of the thumbnail bucket
    Value: !GetAtt ThumbnailBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ThumbnailBucketArn'

